//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IntrEx.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_TIMER                        101
#define IDD_INTREX_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_PARAM_DLG                   129
#define IDS_STR_INPORT                  129
#define IDS_STR_SW_TIMER                130
#define IDD_PROPTRG                     133
#define IDD_CAMSEL                      137
#define IDD_GRABTRIG                    147
#define IDC_EDIT_VB                     1000
#define IDC_EDIT_ODD_VB                 1001
#define IDC_EDIT_EVEN_VB                1002
#define IDC_EDIT_EOFRM                  1003
#define IDC_EDIT_SOT                    1004
#define IDC_EDIT_BMDONE                 1005
#define IDC_EDIT_START_OF_FIELD         1006
#define IDC_EDIT_START_OF_ODD           1007
#define IDC_EDIT_START_OF_EVEN          1008
#define IDC_EDIT_START_OF_FRAME         1009
#define IDC_EDIT_BMDONE2                1010
#define IDC_EDIT_BMDONE3                1011
#define IDC_EDIT_SKIPPED_FIELD          1012
#define IDC_POLFALL                     1013
#define IDC_FALLING_EDGE                1013
#define IDC_EDIT_INPORT                 1013
#define IDC_EDIT_LOSS_OF_SYNC           1014
#define IDC_TACTHIGH                    1014
#define IDC_RISING_EDGE                 1014
#define IDC_TTLTRIG                     1015
#define IDC_TRGAPPLY                    1015
#define IDC_EDIT_TRIG_SKIP              1015
#define IDC_OPTO_COUPLED                1016
#define IDC_DIFFERENTIAL2               1016
#define IDC_EDIT_ODD_SWT                1016
#define IDC_EDIT_AIO_FIFO_OVR           1017
#define IDC_TRGTIME                     1017
#define IDC_EDIT_DECISION_ABSENT        1018
#define IDC_BUTTON1                     1018
#define IDC_TTL_2                       1018
#define IDC_SW_TRIG                     1019
#define IDC_EDIT_DECISION_LATE          1019
#define IDC_EDIT_EVEN_DP0               1020
#define IDC_EDIT_EVEN_DP1               1021
#define IDC_TTL_1                       1022
#define IDC_EDIT_EVEN_DP2               1022
#define IDC_EDIT_EVEN_DP3               1023
#define IDC_EDIT_EVEN_DP4               1024
#define IDC_EDIT_EVEN_DP5               1025
#define IDC_EDIT_EVEN_DP6               1026
#define IDC_EDIT_EVEN_DP7               1027
#define IDC_LIST_CAMNAME                1028
#define IDC_GRAB_ACTIVE                 1040
#define IDC_TRIG_SRC                    1040
#define IDC_RADIO2                      1041
#define IDC_TRG_DISABLE                 1041
#define IDC_EXT_TRG_INPUT               1044
#define IDC_RADIO6                      1045
#define IDC_RADIO7                      1046
#define IDC_DISABLE_TRIG                1047
#define IDC_RADIO8                      1047
#define IDC_ENABLE_TRIG                 1048
#define IDC_TRIG_ACTIVE_LEVEL           1048
#define IDC_RADIO10                     1049
#define IDC_RESET                       1049
#define IDC_PIO_POLAR                   1050
#define IDC_RADIO3                      1051
#define IDC_STROBE_ENABLE               1052
#define IDC_RADIO4                      1053
#define IDC_STROBE_POL                  1054
#define IDC_RADIO9                      1055
#define IDC_TRIG_END_DISABLE            1055
#define IDC_STROBE_MODE                 1056
#define IDC_RADIO12                     1057
#define IDC_RADIO11                     1057
#define IDC_STROBE_DELAY                1058
#define IDC_FRAME_RESET                 1059
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_FRAME_RESET_POL             1061
#define IDC_RADIO15                     1061
#define IDC_RADIO16                     1062
#define IDC_TRIG_START_DISABLE          1062
#define IDC_FRAME_RESET_LENGTH          1063
#define IDC_RADIO18                     1064
#define ID_APPLY                        1064
#define IDC_FRAME_RESET_OUTPUT          1065
#define IDC_RADIO20                     1066
#define IDC_FRAME_RESET_PERIOD          1067
#define IDC_SOFT_TRIG                   1068
#define IDC_SETUP_TRIG                  1069
#define IDC_APPLY                       1070
#define IDC_SOFT_SW_TIMER               1070
#define IDC_CANCEL                      1071
#define IDC_TRG_ENABLE                  1073
#define IDC_BUTTON_ENABLE_VB            1122
#define IDC_BUTTON_ENABLE_ODD_VB        1123
#define IDC_BUTTON_ENABLE_EVEN_VB       1124
#define IDC_BUTTON_ENABLE_EOFRM         1125
#define IDC_BUTTON_ENABLE_SOT           1126
#define IDC_BUTTON_ENABLE_BMDONE        1127
#define IDC_BUTTON_ENABLE_SO_FIELD      1128
#define IDC_BUTTON_ENABLE_SO_ODD        1129
#define IDC_BUTTON_ENABLE_SO_EVEN       1130
#define IDC_BUTTON_ENABLE_SO_FRAME      1131
#define IDC_BUTTON_ENABLE_BMDONE2       1132
#define IDC_BUTTON_ENABLE_BMDONE3       1133
#define IDC_BUTTON_ENABLE_SKIPPED_FIELD 1134
#define IDC_BUTTON_ENABLE_INPORT        1135
#define IDC_BUTTON_ENABLE_LOSS_OF_SYNC  1136
#define IDC_BUTTON_ENABLE_TRIGSKIP      1137
#define IDC_BUTTON_ENABLE_ODD_SWT       1138
#define IDC_BUTTON_ENABLE_AIO_FIFO_OVR  1139
#define IDC_BUTTON_ENABLE_DECISION_ABSENT 1140
#define IDC_BUTTON_ENABLE_DECISION_LATE 1141
#define IDC_BUTTON_ENABLE_EVEN_DP0      1142
#define IDC_BUTTON_ENABLE_EVEN_DP1      1143
#define IDC_BUTTON_ENABLE_EVEN_DP2      1144
#define IDC_BUTTON_ENABLE_EVEN_DP3      1145
#define IDC_BUTTON_ENABLE_EVEN_DP4      1146
#define IDC_BUTTON_ENABLE_EVEN_DP5      1147
#define IDC_BUTTON_ENABLE_EVEN_DP6      1148
#define IDC_BUTTON_ENABLE_EVEN_DP7      1149
#define IDC_TTL_0                       1160
#define IDC_BUTTON_DISABLE_VB           1160
#define IDC_BUTTON_DISABLE_ODD_VB       1161
#define IDC_BUTTON_DISABLE_EVEN_VB      1162
#define IDC_BUTTON_DISABLE_EOFRM        1163
#define IDC_BUTTON_DISABLE_SOT          1164
#define IDC_BUTTON_DISABLE_BMDONE       1165
#define IDC_BUTTON_DISABLE_SO_FIELD     1166
#define IDC_BUTTON_DISABLE_SO_ODD       1167
#define IDC_BUTTON_DISABLE_SO_EVEN      1168
#define IDC_BUTTON_DISABLE_SO_FRAME     1169
#define IDC_BUTTON_DISABLE_BMDONE2      1170
#define IDC_BUTTON_DISABLE_BMDONE3      1171
#define IDC_BUTTON_DISABLE_SKIPPED_FIELD 1172
#define IDC_BUTTON_DISABLE_INPORT       1173
#define IDC_BUTTON_DISABLE_LOSS_OF_SYNC 1174
#define IDC_BUTTON_DISABLE_TRIGSKIP     1175
#define IDC_BUTTON_DISABLE_ODD_SWT      1176
#define IDC_BUTTON_DISABLE_AIO_FIFO_OVR 1177
#define IDC_BUTTON_DISABLE_DECISION_ABSENT 1178
#define IDC_BUTTON_DISABLE_DECISION_LATE 1179
#define IDC_BUTTON_DISABLE_EVEN_DP0     1180
#define IDC_BUTTON_DISABLE_EVEN_DP1     1181
#define IDC_BUTTON_DISABLE_EVEN_DP2     1182
#define IDC_BUTTON_DISABLE_EVEN_DP3     1183
#define IDC_BUTTON_DISABLE_EVEN_DP4     1184
#define IDC_BUTTON_DISABLE_EVEN_DP5     1185
#define IDC_BUTTON_DISABLE_EVEN_DP6     1186
#define IDC_BUTTON_DISABLE_EVEN_DP7     1187

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
