#if !defined(AFX_ITICONFIG_H__DD2CA317_BFF0_11D4_A409_005004051D9B__INCLUDED_)
#define AFX_ITICONFIG_H__DD2CA317_BFF0_11D4_A409_005004051D9B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CITIConfig wrapper class

class CITIConfig : public CWnd
{
protected:
	DECLARE_DYNCREATE(CITIConfig)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8a4452a5, 0x9327, 0x11d3, { 0x96, 0xc2, 0xe3, 0x2c, 0xa5, 0xcd, 0xf0, 0x4e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetReadyState();
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetBorderStyle();
	void SetBorderStyle(short);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	short GetAppearance();
	void SetAppearance(short);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	COleFont GetCustomFont();
	void SetCustomFont(LPDISPATCH);
	unsigned long GetBoardColor();
	void SetBoardColor(unsigned long);

// Operations
public:
	void SetMod(long pMod, long bRegEdit, long bEnaSave, long bEnaParamEvent);
	void EnableParamHelp(short bEnable);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ITICONFIG_H__DD2CA317_BFF0_11D4_A409_005004051D9B__INCLUDED_)
