//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by seqsnap.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SEQSNATYPE                  129
#define IDS_STR_TRIG0                   129
#define IDD_DLGSNAP                     130
#define IDS_STR_TRIG1                   130
#define IDD_PROPTRG                     133
#define IDD_PROPSTRB                    134
#define IDD_PROPRESET                   135
#define IDD_CAMSEL                      137
#define IDD_LUTFLOOR                    142
#define IDD_OUTPORT                     143
#define IDD_DLGWIN                      144
#define IDD_HWZOOM                      145
#define IDD_DUAL_TAP                    146
#define IDD_GRABTRIG                    147
#define IDD_COLOR                       148
#define IDI_RED                         148
#define IDB_RED_BUTTON                  149
#define IDD_COLOR_SPACE_CONV            149
#define IDB_GREEN_BUTTON                150
#define IDD_CONFIG                      150
#define IDB_RGB_BUTTON                  152
#define IDB_BLUE_BUTTON                 153
#define IDB_RGB_24_BUTTON               154
#define IDB_aRGB_PLANAR_BUTTON          155
#define IDB_RGB_PLANAR_BUTTON           156
#define IDC_SLIDER2                     1001
#define IDC_SNAP                        1002
#define IDC_NUMFRAMES                   1005
#define IDC_PLAY                        1007
#define IDC_EXTTRIG                     1011
#define IDC_TrigDifferential            1011
#define IDC_DIFFERENTIAL                1011
#define IDC_TTL_0                       1012
#define IDC_TACTLOW                     1013
#define IDC_POLFALL                     1013
#define IDC_FALLING_EDGE                1013
#define IDC_TACTHIGH                    1014
#define IDC_RISING_EDGE                 1014
#define IDC_TRGSTART                    1015
#define IDC_TTLTRIG                     1015
#define IDC_TRGSTOP                     1016
#define IDC_OPTO_COUPLED                1016
#define IDC_TRGTIME                     1017
#define IDC_STRBFAST                    1018
#define IDC_SKIP_ENB                    1018
#define IDC_TTL_2                       1018
#define IDC_STRBSLOW                    1019
#define IDC_SKIP_DISABLE                1019
#define IDC_SW_TRIG                     1019
#define IDC_FRPLOW                      1020
#define IDC_EXT_INPUT0                  1020
#define IDC_FRPHI                       1021
#define IDC_EXT_INPUT1                  1021
#define IDC_STRBPLOW                    1022
#define IDC_FROFFPER                    1022
#define IDC_EXT_INPUT2                  1022
#define IDC_TTL_1                       1022
#define IDC_STRBPHI                     1023
#define IDC_FRONELINE                   1023
#define IDC_EXT_INPUT3                  1023
#define IDC_GD_ENABLE                   1023
#define IDC_OPTO_COUPLED_0              1023
#define IDC_FROFF                       1024
#define IDC_STRB_ENB                    1024
#define IDC_GD_DISABLE                  1024
#define IDC_OPTO_COUPLED_1              1024
#define IDC_STRBDLY                     1025
#define IDC_FRONVSYNC                   1025
#define IDC_FRENABLE                    1026
#define IDC_STRB_DIS                    1026
#define IDC_FRDISABLE                   1027
#define IDC_LIST_CAMNAME                1027
#define IDC_LIST_PORT                   1028
#define IDC_FRONOUTPUT                  1028
#define IDC_LUTTHRESH                   1032
#define IDC_OUTPORT_VAL                 1033
#define IDC_GENSTROBE                   1034
#define IDC_WGEN_X                      1035
#define IDC_WGEN_Y                      1036
#define IDC_EDIT5                       1037
#define IDC_STATIC3                     1038
#define IDC_WGEN_DX                     1039
#define IDC_XZ_NO                       1039
#define IDC_XZ_2                        1040
#define IDC_XZ_FACTOR_2                 1040
#define IDC_YZ_NO                       1041
#define IDC_LIVE                        1041
#define IDC_STATIC4                     1042
#define IDC_YZ_2                        1042
#define IDC_YZ_FACTOR_2                 1042
#define IDC_WGEN_DY                     1043
#define IDC_XZ_8                        1043
#define IDC_XZ_FACTOR_4                 1043
#define IDC_XZ_4                        1044
#define IDC_YZ_8                        1045
#define IDC_YZ_FACTOR_4                 1045
#define IDC_YZ_4                        1046
#define IDC_X_ABS                       1046
#define IDC_X_REL                       1047
#define IDC_Y_ABS                       1048
#define IDC_RADIO1                      1048
#define IDC_RADIO_RED                   1048
#define IDC_Y_REL                       1049
#define IDC_RADIO3                      1049
#define IDC_RADIO_RGB                   1049
#define IDC_RADIO2                      1050
#define IDC_GP_OUTPUT1                  1050
#define IDC_RADIO_RGB_24                1050
#define IDC_RADIO5                      1051
#define IDC_RADIO4                      1051
#define IDC_RADIO_RGB_PLANAR            1051
#define IDC_GP_OUTPUT0                  1052
#define IDC_RADIO6                      1052
#define IDC_RADIO_aRGB_PLANAR           1052
#define IDC_RADIO7                      1053
#define IDC_RADIO_BLUE                  1053
#define IDC_RADIO8                      1054
#define IDC_TRIG_END_DISABLE            1055
#define IDC_RADIO10                     1056
#define IDC_RADIO11                     1057
#define IDC_RADIO12                     1058
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_RADIO15                     1061
#define IDC_TRIG_START_DISABLE          1062
#define ID_APPLY                        1064
#define IDC_RADIO_GREEN                 1065
#define IDC_RADIO_RGB_TO_YUV            1066
#define IDC_RADIO_RGB_TO_YIQ            1067
#define IDC_RADIO_RGB_TO_YCRCB_4_4_4    1068
#define IDC_RADIO_RGB_TO_RGB            1069
#define IDC_RADIO_RGB_TO_HSI            1071
#define IDC_ITICONFIGCTRL1              1072
#define IDC_SAVESEQ                     1073
#define ID_CMDS_SEQSNAP                 32771
#define ID_CMDS_TRIGOPS                 32772
#define ID_CMDS_SELECTCAM               32773
#define ID_CMDS_WRITETIFF               32775
#define ID_CMDS_READTIFF                32776
#define ID_CMDS_HWOVERLAY               32779
#define ID_CMDS_PERFORMANCE             32780
#define ID_LUT_LINEAR                   32782
#define ID_LUT_INVERT                   32783
#define ID_LUT_THRESH                   32785
#define ID_CMDS_OUTPORT                 32786
#define ID_CMDS_INPORT                  32787
#define ID_CMDS_WINDOWGEN               32788
#define ID_CMDS_HWZOOM                  32789
#define ID_CMDS_SWOVERLAY               32790
#define ID_CMDS_DUALTAP                 32791
#define ID_PARAMS                       32792
#define ID_BRD_PARAMS                   32793
#define ID_CMDS_SNAP                    32794
#define ID_CMDS_COLOR                   32795
#define ID_CMDS_COLOR_SPACE_CONV        32796
#define ID_CONFIG                       32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
