function files = getsegfiles;

files = ['seg1b.mat'; ...
         'seg2b.mat'; ...
         'seg3b.mat'; ...
         'seg4b.mat'; ...
         'seg5b.mat'; ...
         'seg6b.mat'; ...
         'seg7.mat '; ...
         'seg8.mat '; ...
         'seg9.mat '; ...
         'seg10.mat'; ...
         'seg11.mat'; ...
         'seg12.mat'; ...
         'seg13.mat'; ...
         'seg14.mat'; ...
         'seg15.mat'; ...
         'seg16.mat'; ...
         'seg17.mat'; ...
         'seg18.mat'; ...
         'seg19.mat'];