//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by seqsnap.rc
//
#define IDRESET                         3
#define IDD_ABOUTBOX                    100
#define UM_KILLME                       101
#define IDR_MAINFRAME                   128
#define IDR_SEQSNATYPE                  129
#define IDS_STR_TRIG0                   129
#define IDD_DLGSNAP                     130
#define IDS_STR_TRIG1                   130
#define IDD_PROPTRG                     133
#define IDD_PROPSTRB                    134
#define IDD_PROPRESET                   135
#define IDD_CAMSEL                      137
#define IDD_LUTFLOOR                    142
#define IDD_OUTPORT                     143
#define IDD_DLGWIN                      144
#define IDD_HWZOOM                      145
#define IDD_DUAL_TAP                    146
#define IDD_GRABTRIG                    147
#define IDD_COLOR                       148
#define IDI_RED                         148
#define IDB_RED_BUTTON                  149
#define IDD_COLOR_SPACE_CONV            149
#define IDB_GREEN_BUTTON                150
#define IDB_RGB_BUTTON                  152
#define IDB_BLUE_BUTTON                 153
#define IDB_RGB_24_BUTTON               154
#define IDB_aRGB_PLANAR_BUTTON          155
#define IDB_RGB_PLANAR_BUTTON           156
#define IDC_SLIDER2                     1001
#define IDC_SNAP                        1002
#define IDC_NUMFRAMES                   1005
#define IDC_PLAY                        1007
#define IDC_EX_TRIG                     1012
#define IDC_TACTLOW                     1013
#define IDC_POLFALL                     1013
#define IDC_FALLING_EDGE                1013
#define IDC_TACTHIGH                    1014
#define IDC_RISING_EDGE                 1014
#define IDC_TRGSTART                    1015
#define IDC_TTLTRIG                     1015
#define IDC_TRGSTOP                     1016
#define IDC_TRGTIME                     1017
#define IDC_STRBFAST                    1018
#define IDC_SKIP_ENB                    1018
#define IDC_STRBSLOW                    1019
#define IDC_SKIP_DISABLE                1019
#define IDC_SW_TRIG                     1019
#define IDC_FRPLOW                      1020
#define IDC_FRPHI                       1021
#define IDC_STRBPLOW                    1022
#define IDC_FROFFPER                    1022
#define IDC_STRBPHI                     1023
#define IDC_FRONELINE                   1023
#define IDC_GD_ENABLE                   1023
#define IDC_OPTO_COUPLED_0              1023
#define IDC_FROFF                       1024
#define IDC_STRB_ENB                    1024
#define IDC_GD_DISABLE                  1024
#define IDC_OPTO_COUPLED_1              1024
#define IDC_STRBDLY                     1025
#define IDC_FRONVSYNC                   1025
#define IDC_FRENABLE                    1026
#define IDC_STRB_DIS                    1026
#define IDC_FRDISABLE                   1027
#define IDC_LIST_CAMNAME                1027
#define IDC_LIST_PORT                   1028
#define IDC_FRONOUTPUT                  1028
#define IDC_LUTTHRESH                   1032
#define IDC_OUTPORT_VAL                 1033
#define IDC_GENSTROBE                   1034
#define IDC_WGEN_X                      1035
#define IDC_WGEN_Y                      1036
#define IDC_EDIT5                       1037
#define IDC_STATIC3                     1038
#define IDC_WGEN_DX                     1039
#define IDC_XZ_NO                       1039
#define IDC_XZ_2                        1040
#define IDC_XZ_FACTOR_2                 1040
#define IDC_YZ_NO                       1041
#define IDC_LIVE                        1041
#define IDC_STATIC4                     1042
#define IDC_YZ_2                        1042
#define IDC_YZ_FACTOR_2                 1042
#define IDC_WGEN_DY                     1043
#define IDC_XZ_8                        1043
#define IDC_XZ_FACTOR_4                 1043
#define IDC_XZ_4                        1044
#define IDC_XZ_FACTOR_8                 1044
#define IDC_YZ_8                        1045
#define IDC_YZ_FACTOR_4                 1045
#define IDC_YZ_4                        1046
#define IDC_X_ABS                       1046
#define IDC_YZ_FACTOR_8                 1046
#define IDC_X_REL                       1047
#define IDC_Y_ABS                       1048
#define IDC_RADIO1                      1048
#define IDC_RADIO_RED                   1048
#define IDC_SLOWSTROBE                  1048
#define IDC_PORT0                       1048
#define IDC_Y_REL                       1049
#define IDC_RADIO3                      1049
#define IDC_RADIO_RGB                   1049
#define IDC_STROBE_POL_LOW              1049
#define IDC_PORT1                       1049
#define IDC_XZ_3                        1049
#define IDC_RADIO2                      1050
#define IDC_GP_OUTPUT1                  1050
#define IDC_RADIO_RGB_24                1050
#define IDC_FASTSTROBE                  1050
#define IDC_PORT2                       1050
#define IDC_YZ_3                        1050
#define IDC_RADIO5                      1051
#define IDC_RADIO4                      1051
#define IDC_RADIO_RGB_PLANAR            1051
#define IDC_STROBE_POL_HI               1051
#define IDC_PORT3                       1051
#define IDC_GP_OUTPUT0                  1052
#define IDC_RADIO6                      1052
#define IDC_RADIO_aRGB_PLANAR           1052
#define IDC_FRAME_POL_LOW               1052
#define IDC_PORT4                       1052
#define IDC_RADIO7                      1053
#define IDC_RADIO_BLUE                  1053
#define IDC_FRAME_POL_HI                1053
#define IDC_PORT5                       1053
#define IDC_RADIO8                      1054
#define IDC_FRAME_ENABLE                1054
#define IDC_TRIG_END_DISABLE            1055
#define IDC_FRAME_DISABLE               1055
#define IDC_RADIO10                     1056
#define IDC_FRAME_SIZE_PERIOD           1056
#define IDC_RADIO11                     1057
#define IDC_FRAME_SIZE_LINE             1057
#define IDC_RADIO12                     1058
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_STROBE_DISABLE              1060
#define IDC_RADIO15                     1061
#define IDC_STROBE_ENABLE               1061
#define IDC_TRIG_START_DISABLE          1062
#define IDC_TRIGGER_ENABLE              1062
#define IDC_TRIGGER_DISABLE             1063
#define ID_APPLY                        1064
#define IDC_RADIO_GREEN                 1065
#define IDC_RADIO_RGB_TO_YUV            1066
#define IDC_RADIO_RGB_TO_YIQ            1067
#define IDC_RADIO_RGB_TO_YCRCB_4_4_4    1068
#define IDC_RADIO_RGB_TO_YCRCB_4_2_2    1069
#define IDC_RADIO_RGB_TO_YCBCR_4_2_2    1070
#define IDC_RADIO_RGB_TO_HSI            1071
#define IDC_STROBE_DELAY                1072
#define IDC_STROBE_DELAY_E              1073
#define IDC_FRAME_DELAY                 1074
#define IDC_FRAME_DELAY_E               1075
#define IDC_SOFT_TRIG                   1076
#define IDC_FRAME_RESET_SIZE            1076
#define IDC_TTL0_TRIG                   1077
#define IDC_TTL1_TRIG                   1078
#define IDC_TTL2_TRIG                   1079
#define IDC_OPTO0_TRIG                  1080
#define IDC_OPTO1_TRIG                  1081
#define IDC_DIFF0_TRIG                  1082
#define IDC_DIFF1_TRIG                  1083
#define IDC_CONTINUOUS                  1086
#define IDC_IMAGES_NUM                  1087
#define IDC_STATIC1                     1088
#define IDC_STATIC2                     1089
#define IDC_Y_START                     1090
#define IDC_Y_END                       1091
#define IDC_THRESHOLD                   1092
#define IDC_SAVE                        1093
#define IDC_FRAME_TIME                  1094
#define IDC_TOTAL_TIME                  1095
#define IDC_SAVEAVI                     1096
#define IDC_XZOOM                       1105
#define IDC_YZOOM                       1106
#define IDC_TRGSRC_SOFT                 1106
#define IDC_TSRC_EXT0                   1107
#define IDC_TSRC_EXT1                   1108
#define IDC_TSRC_EXT_AUTO               1109
#define IDC_RELATIVE                    2000
#define IDC_ABSOLUTE                    2003
#define ID_CMDS_SEQSNAP                 32771
#define ID_CMDS_TRIGOPS                 32772
#define ID_CMDS_SELECTCAM               32773
#define ID_CMDS_WRITETIFF               32775
#define ID_CMDS_READTIFF                32776
#define ID_CMDS_HWOVERLAY               32779
#define ID_CMDS_PERFORMANCE             32780
#define ID_LUT_LINEAR                   32782
#define ID_LUT_INVERT                   32783
#define ID_LUT_THRESH                   32785
#define ID_CMDS_WINDOWGEN               32788
#define ID_CMDS_HWZOOM                  32789
#define ID_CMDS_SWOVERLAY               32790
#define ID_CMDS_DUALTAP                 32791
#define ID_PARAMS                       32792
#define ID_BRD_PARAMS                   32793
#define ID_CMDS_SNAP                    32794
#define ID_CMDS_ADVANCEDIO              32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
