//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IntrEx.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_TIMER                        101
#define IDD_INTREX_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_PARAM_DLG                   129
#define IDS_STR_INPORT                  129
#define IDS_STR_SW_TIMER                130
#define IDD_PROPTRG                     133
#define IDD_CAMSEL                      137
#define IDD_GRABTRIG                    147
#define IDC_EDIT_SOT                    1000
#define IDC_EDIT_EOT                    1001
#define IDC_EDIT_INPORT                 1002
#define IDC_EDIT_SW_TIMER               1003
#define IDC_EDIT_ACQ_ADRS               1004
#define IDC_EDIT_BMDONE                 1005
#define IDC_EDIT_AM_CASCADE             1006
#define IDC_EDIT_EOFRM                  1007
#define IDC_EDIT_VB                     1008
#define IDC_EDIT_EVEN_VB                1009
#define IDC_EDIT_ODD_VB                 1010
#define IDC_TrigDifferential            1011
#define IDC_DIFFERENTIAL                1011
#define IDC_TTL_0                       1012
#define IDC_POLFALL                     1013
#define IDC_FALLING_EDGE                1013
#define IDC_TACTHIGH                    1014
#define IDC_RISING_EDGE                 1014
#define IDC_TTLTRIG                     1015
#define IDC_TRGAPPLY                    1015
#define IDC_OPTO_COUPLED                1016
#define IDC_TRGTIME                     1017
#define IDC_BUTTON1                     1018
#define IDC_TTL_2                       1018
#define IDC_BUTTON2                     1019
#define IDC_SW_TRIG                     1019
#define IDC_BUTTON3                     1020
#define IDC_BUTTON4                     1021
#define IDC_BUTTON5                     1022
#define IDC_TTL_1                       1022
#define IDC_BUTTON6                     1023
#define IDC_GD_ENABLE                   1023
#define IDC_OPTO_COUPLED_0              1023
#define IDC_BUTTON7                     1024
#define IDC_GD_DISABLE                  1024
#define IDC_OPTO_COUPLED_1              1024
#define IDC_BUTTON8                     1025
#define IDC_BUTTON9                     1026
#define IDC_BUTTON0A                    1027
#define IDC_BUTTON0B                    1028
#define IDC_LIST_CAMNAME                1027
#define IDC_BUTTON10                    1029
#define IDC_BUTTON11                    1030
#define IDC_BUTTON12                    1031
#define IDC_BUTTON13                    1032
#define IDC_BUTTON14                    1033
#define IDC_BUTTON15                    1034
#define IDC_BUTTON16                    1035
#define IDC_BUTTON17                    1036
#define IDC_BUTTON18                    1037
#define IDC_BUTTON19                    1038
#define IDC_BUTTON1A                    1039
#define IDC_TRIG_SRC                    1040
#define IDC_RADIO2                      1041
#define IDC_EXT_TRG_INPUT               1044
#define IDC_RADIO6                      1045
#define IDC_RADIO7                      1046
#define IDC_DISABLE_TRIG                1047
#define IDC_RADIO8                      1047
#define IDC_ENABLE_TRIG                 1048
#define IDC_TRIG_ACTIVE_LEVEL           1048
#define IDC_RADIO10                     1049
#define IDC_RESET                       1049
#define IDC_PIO_POLAR                   1050
#define IDC_RADIO3                      1051
#define IDC_STROBE_ENABLE               1052
#define IDC_RADIO4                      1053
#define IDC_STROBE_POL                  1054
#define IDC_RADIO9                      1055
#define IDC_TRIG_END_DISABLE            1055
#define IDC_STROBE_MODE                 1056
#define IDC_RADIO12                     1057
#define IDC_RADIO11                     1057
#define IDC_STROBE_DELAY                1058
#define IDC_FRAME_RESET                 1059
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_FRAME_RESET_POL             1061
#define IDC_RADIO15                     1061
#define IDC_RADIO16                     1062
#define IDC_TRIG_START_DISABLE          1062
#define IDC_FRAME_RESET_LENGTH          1063
#define IDC_RADIO18                     1064
#define ID_APPLY                        1064
#define IDC_FRAME_RESET_OUTPUT          1065
#define IDC_RADIO20                     1066
#define IDC_FRAME_RESET_PERIOD          1067
#define IDC_SOFT_TRIG                   1068
#define IDC_SETUP_TRIG                  1069
#define IDC_APPLY                       1070
#define IDC_SOFT_SW_TIMER               1070
#define IDC_CANCEL                      1071
#define IDC_TRG_ENABLE                  1073
#define IDC_GRAB_ACTIVE                 1074

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
