/******************************************************************************
 *
 * MODULE   
 *		PCPlust.h
 *
 * REVISION INFORMATION  
 *		$Logfile: /ifc/VegaNet/include/pcplust.h $
 *		$Revision: 1.1 $
 *		$Modtime: 2/22/01 10:44a $
 *
 * ABSTRACT  
 *		VS interface of the PCVisionPlus video source.
 *
 * TECHNICAL NOTES 
 *
 *
 * Copyright (c) 2000-2001 Imaging Technology, Inc.  All rights reserved.
 *
 ******************************************************************************/

#if !defined(AFX_PCPLUST_H__582D6F70_E7BC_11D2_B53F_00A0C99ACB20__INCLUDED_)
#define AFX_PCPLUST_H__582D6F70_E7BC_11D2_B53F_00A0C99ACB20__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include <vidsrct.h>

typedef enum VPCP_PWG_FLD_POL_TYPE {
	VPCP_LOW_IS_ODD,
	VPCP_LOW_IS_EVEN
} VPCP_PWG_FLD_POL_TYPE;

typedef enum VPCP_FLD_SRC_TYPE {
	VPCP_FLD_SRC_SYNC_STRIPPER,
	VPCP_FLD_SRC_BASED_ON_H_AND_V_SYNC
} VPCP_FLD_SRC_TYPE;

typedef enum  VPCP_LPF_TYPE {
	VPCP_LPF_6_5_MHZ,
	VPCP_LPF_12_5_MHZ
} VPCP_LPF_TYPE;

typedef enum VPCP_INTFLT_TYPE {
	VPCP_EXTERNAL_LOOP_FILTER,
	VPCP_INTERNAL_LOOP_FILTER
} VPCP_INTFLT_TYPE;	


typedef enum VPCP_CLAMP_SRC_TYPE {
	VPCP_SYNC_STRIPPER_BACK_PORCH,
	VPCP_PROGRAMMABLE
} VPCP_CLAMP_SRC_TYPE;

typedef enum VPCP_VSCAN_CLOCKSEL {
	VPCP_VSCAN_CLKSEL_NORMAL,
	VPCP_VSCAN_CLKSEL_FRESET
} VPCP_VSCAN_CLOCKSEL;


#define VPCP_NUM_LUT_ENTRIES 0x10000

typedef enum VPCP_TRIG_SRC_TYPE {
	VPCP_SOFT_TRIG,
	VPCP_EXT_TRIG0,
	VPCP_EXT_TRIG1,
	VPCP_EXT_TRIG2,
	VPCP_OPTO_COUPLED_TRIG0,
	VPCP_OPTO_COUPLED_TRIG1,
	VPCP_RS422_DIFF_TRIG0,
	VPCP_RS422_DIFF_TRIG1
} VPCP_TRIG_SRC_TYPE; 

typedef enum VPCP_PRGM_CLAMP_REF_POINT_TYPE {
	VPCP_CREF_HSYNC_FROM_STRIPPER,
	VPCP_CREF_TIMING_MODE_DEPENDANT	

} VPCP_PRGM_CLAMP_REF_POINT_TYPE;



typedef enum VPCP_PARAMS_TYPE {

	VPCP_FIELD_SRC = VSP_MOD_UNIQUE_BASE,			// VS_ENABLE_TYPE

	VPCP_SKIP_FIELD_MODE,
	VPCP_FRAME_RESET_ON_VSYNC_OUTPUT,
	VPCP_TRIG_CYCLE_LATCH_TRIG,
	VPCP_A_TO_D_PREF,
	VPCP_A_TO_D_NREF,
	VPCP_LOW_PASS_FILTER,
	VPCP_PWG_FIELD_POLARITY,
	VPCP_FIELD_SHIFT,
	VPCP_PTG_VSYNC_OUT_EN,

	VPCP_CLAMP_SOURCE,
	VPCP_BACK_PORCH_CLAMP_START,
	VPCP_BACK_PORCH_CLAMP_END,
	VPCP_NO_CLAMP_REGION,
	VPCP_PRGM_CLAMP_REF_POINT,


	VPCP_EDONPISHA_MODE,
	VPCP_PTG2PWG_HSYNC_FLIP,
	VPCP_OVERSAMPLE_MODE,
	VPCP_VSCAN_CLKSEL,
	VPCP_LOOP_FILTER,

	VPCP_PARAM_END_MARKER
} VPCP_PARAMS_TYPE;


typedef enum VPCP_PARAM_GROUP_TYPE{
	VPCP_PGRP_REF_VOLTAGE=VS_PGRP_MOD_PECULIAR1,
	VPCP_PGRP_CLAMP_SETTINGS

} VPCP_PARAM_GROUP_TYPE;

#define VPCP_PGRP_REF_VOLTAGE_MASK		PGRP_ID_TO_MASK(VPCP_PGRP_REF_VOLTAGE)
#define VPCP_PGRP_CLAMP_SETTINGS_MASK	PGRP_ID_TO_MASK(VPCP_PGRP_CLAMP_SETTINGS)


#define VPCP_NUM_PARAMS (GEN_PARAM_END_MARKER+VPCP_PARAM_END_MARKER-VPCP_PECULIAR_PARAM_BASE)


#endif // !defined(AFX_PCPLUST_H__582D6F70_E7BC_11D2_B53F_00A0C99ACB20__INCLUDED_)
