/******************************************************************************
 *
 * MODULE   
 *		PCRgbt.h
 *
 * REVISION INFORMATION  
 *		$Logfile: /ifc/VegaNet/include/PCRgbt.h $
 *		$Revision: 1.1 $
 *		$Modtime: 2/22/01 11:04a $
 *
 * ABSTRACT  
 *		VegaNet interface of the PC-RGB video source.
 *
 * TECHNICAL NOTES 
 *
 *
 * Copyright (c) 1999-2001 Imaging Technology, Inc.  All rights reserved.
 *
 ******************************************************************************/

#if !defined(AFX_PCRGBT_H__582D6F70_E7BC_11D2_B53F_00A0C99ACB20__INCLUDED_)
#define AFX_PCRGBT_H__582D6F70_E7BC_11D2_B53F_00A0C99ACB20__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000




typedef enum VPCR_PWG_FLD_POL_TYPE {
	VPCR_LOW_IS_ODD,
	VPCR_LOW_IS_EVEN
} VPCR_PWG_FLD_POL_TYPE;

typedef enum VPCR_FLD_SRC_TYPE {
	VPCR_FLD_SRC_SYNC_STRIPPER,
	VPCR_FLD_SRC_GENERATED_BASED_ON_H_AND_V_SYNC
} VPCR_FLD_SRC_TYPE;

typedef enum VPCR_LPF_TYPE {
	VPCR_LPF_6MHZ,
	VPCR_LPF_10MHZ
} VPCR_LPF_TYPE;


typedef enum VPCR_SYNC_STRIPPER_SRC_TYPE {
	VPCR_GREEN_VIDEO_CHANNEL,
	VPCR_COMPOSITE_CHANNEL_0,
	VPCR_COMPOSITE_CHANNEL_1
} VPCR_SYNC_STRIPPER_SRC_TYPE;

typedef enum VPCR_CLAMP_SRC_TYPE {
	VPCR_SYNC_STRIPPER_BACK_PORCH,
	VPCR_PROGRAMMABLE
} VPCR_CLAMP_SRC_TYPE;

#define VPCR_NUM_LUT_ENTRIES 0x10000

typedef enum VPCR_TRIG_SRC_TYPE {
	VPCR_SOFT_TRIG,
	VPCR_EXT_TRIG0,
	VPCR_EXT_TRIG1,
	VPCR_EXT_TRIG2,
	VPCR_OPTO_COUPLED_TRIG0,
	VPCR_OPTO_COUPLED_TRIG1,
	VPCR_RS422_DIFF_TRIG,
} VPCR_TRIG_SRC_TYPE; 

typedef enum VPCR_PRGM_CLAMP_REF_POINT_TYPE {
	VPCR_CREF_HSYNC_FROM_STRIPPER,
	VPCR_CREF_TIMING_MODE_DEPENDANT	

} VPCR_PRGM_CLAMP_REF_POINT_TYPE;

typedef enum VPCR_MULTITAP_MODE_TYPE {
	VPCR_SINGLE_TAP,
	VPCR_2TAP_ILACE_TOGGLE
} VPCR_MULTITAP_MODE_TYPE;


#define VPCR_PECULIAR_PARAM_BASE (MOD_PECULIAR_PARAM_BASE + 0x1000 * VPCR_PCI_DEVICE_ID)

typedef enum VPCR_PARAMS_TYPE {

	VPCR_FIELD_SRC = VSP_MOD_UNIQUE_BASE,
	VPCR_SKIP_FIELD_MODE,
	VPCR_STROBE_OUTPUT_ENABLE,
	VPCR_FRAME_RESET_ON_VSYNC_OUTPUT,
	VPCR_TRIG_CYCLE_LATCH_TRIG,
	VPCR_RED_A_TO_D_PREF,
	VPCR_GREEN_A_TO_D_PREF,
	VPCR_BLUE_A_TO_D_PREF,
	VPCR_RED_A_TO_D_NREF,
	VPCR_GREEN_A_TO_D_NREF,
	VPCR_BLUE_A_TO_D_NREF,
	VPCR_LOW_PASS_FILTER,
	VPCR_PWG_FIELD_POLARITY,
	VPCR_FIELD_SHIFT,
	VPCR_PTG_VSYNC_OUT_EN,
	VPCR_CLAMP_SOURCE,
	VPCR_SYNC_STRIPPER_SOURCE,
	VPCR_BACK_PORCH_CLAMP_START,
	VPCR_BACK_PORCH_CLAMP_END,
	VPCR_NO_CLAMP_REGION,
	VPCR_PRGM_CLAMP_REF_POINT,
	VPCR_FRONT_PORCH_CLAMP_START,
	VPCR_FRONT_PORCH_CLAMP_END,
	VPCR_FRONT_PORCH_ENABLE,
	VPCR_MULTITAP_MODE,
	VPCR_EDONPISHA_MODE,
	VPCR_PTG2PWG_HSYNC_FLIP,

	VPCR_PARAM_END_MARKER
} VPCR_PARAMS_TYPE;


typedef enum VPCR_PARAM_GROUP_TYPE {
	VPCR_PGRP_COLOR_SPACE_CONV=VS_PGRP_MOD_PECULIAR1,
	VPCR_PGRP_REF_VOLTAGE,
	VPCR_PGRP_CLAMP_SETTINGS

} VPCR_PARAM_GROUP_TYPE;

#define VPCR_PGRP_COLOR_SPACE_CONV_MASK	PGRP_ID_TO_MASK(VPCR_PGRP_COLOR_SPACE_CONV)
#define VPCR_PGRP_REF_VOLTAGE_MASK		PGRP_ID_TO_MASK(VPCR_PGRP_REF_VOLTAGE)
#define VPCR_PGRP_CLAMP_SETTINGS_MASK	PGRP_ID_TO_MASK(VPCR_PGRP_CLAMP_SETTINGS)


#define VPCR_NUM_PARAMS (GEN_PARAM_END_MARKER+VPCR_PARAM_END_MARKER-VPCR_PECULIAR_PARAM_BASE)


#endif // !defined(AFX_PCRGBT_H__582D6F70_E7BC_11D2_B53F_00A0C99ACB20__INCLUDED_)
